# Generated by Django 4.2.20 on 2025-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_to_ndfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedxmlfile',
            name='year',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
