# Generated by Django 4.2.20 on 2025-05-16 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_to_ndfl', '0003_uploadedxmlfile_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedxmlfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Загруженный XML файл', 'verbose_name_plural': 'Загруженные XML файлы'},
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='original_filename',
            field=models.CharField(help_text='Оригинальное имя загруженного файла', max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='xml_file',
            field=models.FileField(upload_to='xml_files/', verbose_name='XML файл'),
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Год отчета, извлеченный из тега <date_end> XML-файла', verbose_name='Год отчета (из XML)'),
        ),
    ]
