# Generated by Django 4.2.20 on 2025-05-16 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports_to_ndfl', '0002_uploadedxmlfile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedxmlfile',
            name='original_filename',
            field=models.CharField(default=1, help_text='Оригинальное имя загруженного файла', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedxmlfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedxmlfile',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Год отчета, извлеченный из <date_end> XML-файла'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadedxmlfile',
            unique_together={('user', 'original_filename', 'year')},
        ),
    ]
