# Generated by Codex on 2026-01-03
from django.db import migrations, models


def migrate_ffg_reports(apps, schema_editor):
    UploadedXMLFile = apps.get_model('reports_to_ndfl', 'UploadedXMLFile')
    BrokerReport = apps.get_model('reports_to_ndfl', 'BrokerReport')

    for old_file in UploadedXMLFile.objects.all():
        BrokerReport.objects.get_or_create(
            user=old_file.user,
            broker_type='ffg',
            original_filename=old_file.original_filename,
            year=old_file.year,
            defaults={
                'report_file': old_file.xml_file,
                'uploaded_at': old_file.uploaded_at,
                'account_number': '',
                'base_currency': 'USD',
            },
        )


def reverse_migrate_ffg_reports(apps, schema_editor):
    BrokerReport = apps.get_model('reports_to_ndfl', 'BrokerReport')
    BrokerReport.objects.filter(broker_type='ffg').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('reports_to_ndfl', '0004_alter_uploadedxmlfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_type', models.CharField(choices=[('ffg', 'Freedom Finance Global'), ('ib', 'Interactive Brokers')], max_length=10, verbose_name='Тип брокера')),
                ('report_file', models.FileField(upload_to='broker_reports/%Y/%m/', verbose_name='Файл отчета')),
                ('year', models.IntegerField(db_index=True, help_text='Год отчета', verbose_name='Год отчета')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счета')),
                ('base_currency', models.CharField(default='USD', max_length=3, verbose_name='Базовая валюта')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Брокерский отчет',
                'verbose_name_plural': 'Брокерские отчеты',
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'broker_type', 'original_filename', 'year')},
            },
        ),
        migrations.RunPython(migrate_ffg_reports, reverse_migrate_ffg_reports),
    ]
