# Generated by Django 4.2.20 on 2025-05-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
                ('char_code', models.CharField(max_length=3, unique=True, verbose_name='Символьный код ISO')),
                ('num_code', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Числовой код ISO')),
                ('cbr_id', models.CharField(help_text='Внутренний ID валюты ЦБ РФ (VAL_NM_RQ)', max_length=10, unique=True, verbose_name='ID ЦБ РФ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['char_code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата курса')),
                ('value', models.DecimalField(decimal_places=4, help_text='Курс за единицу номинала', max_digits=10, verbose_name='Курс')),
                ('nominal', models.PositiveIntegerField(default=1, verbose_name='Номинал')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currency_CBRF.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date', 'currency__char_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date_rate'),
        ),
    ]
