"""
Django settings for NDFL project.

Generated by 'django-admin startproject' using Django 4.2.20.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-dno2seok**vy!5d-48=7=@+@5qw-h+8@uh_wo&c=r)(qj=ri23' # ЗАМЕНИТЕ ДЛЯ ПРОДА

DEBUG = True # Установите False для продакшена

ALLOWED_HOSTS = [] # Настройте для продакшена


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports_to_ndfl.apps.ReportsToNdflConfig', # Ваше приложение
    'currency_CBRF.apps.CurrencyCbrfConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'NDFL.urls' # Имя вашего проекта

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Общая папка шаблонов проекта
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'NDFL.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow' # Укажите ваш часовой пояс
USE_I18N = True
USE_L10N = True 
USE_TZ = True


STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Для collectstatic
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Общая папка static

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Папка для загруженных файлов

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login' 
LOGIN_REDIRECT_URL = 'upload_xml_file' 
LOGOUT_REDIRECT_URL = 'login'

# Настройки API Центрального Банка РФ
CBRF_API_BASE_URL = "http://www.cbr.ru/scripts/"
CBRF_API_TIMEOUT_DAILY = 10  # Таймаут для XML_daily.asp в секундах
CBRF_API_TIMEOUT_PERIOD = 30 # Таймаут для XML_dynamic.asp в секундах
